# Generated by Django 3.1.4 on 2020-12-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201210_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='std',
            field=models.IntegerField(default=1),
        ),
    ]
