# Generated by Django 3.1.4 on 2020-12-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_person_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='std',
            field=models.IntegerField(),
        ),
    ]
