# Generated by Django 3.1.4 on 2020-12-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('hw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_submissions', to='core.homework')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.person')),
            ],
        ),
    ]
