# Generated by Django 3.1.4 on 2020-12-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
