# Generated by Django 3.1.4 on 2020-12-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_room_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='std',
            field=models.IntegerField(default=0),
        ),
    ]
