# Generated by Django 3.1.4 on 2020-12-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_room_std'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(default='Name Not Provided', max_length=15),
        ),
    ]
