# Generated by Django 3.1.4 on 2020-12-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_room_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
