# Generated by Django 3.1.4 on 2020-12-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=69)),
                ('link', models.URLField()),
                ('meeting_id', models.CharField(blank=True, max_length=256)),
                ('password', models.CharField(blank=True, max_length=256)),
                ('std', models.IntegerField()),
            ],
        ),
    ]
