# Generated by Django 3.1.4 on 2020-12-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_room_to_start'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
