# Generated by Django 3.1.4 on 2020-12-15 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=69)),
                ('link', models.URLField()),
                ('meeting_id', models.CharField(blank=True, max_length=256)),
                ('password', models.CharField(blank=True, max_length=256)),
                ('std', models.IntegerField()),
                ('to_start', models.CharField(default='Not Provided / May Start Anytime', max_length=256)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='core.person')),
            ],
        ),
    ]
