# Generated by Django 3.1.4 on 2020-12-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
