# Generated by Django 3.1.4 on 2020-12-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
