# Generated by Django 3.1.4 on 2021-01-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_declared_result_resultsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsubject',
            name='grade',
            field=models.CharField(default='X', max_length=10),
        ),
    ]
