# Generated by Django 3.1.4 on 2021-01-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_resultsubject_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Declared',
        ),
    ]
