# Generated by Django 3.1.4 on 2021-01-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_delete_declared'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaration_status', to='core.result')),
            ],
        ),
    ]
